<?php
session_start();
include('./dbc.php');

// Set timezone for accurate timestamps
date_default_timezone_set('Asia/Colombo'); // Sri Lanka timezone

// Check if user is authenticated
if (!isset($_SESSION['user_id'])) {
    header("Location: login.php");
    exit();
}

// Get current user info
$current_user = isset($_SESSION['username']) ? $_SESSION['username'] : 'SLPA User';
$current_time = date('Y-m-d H:i:s');

// Handle PDF/Excel download
if (isset($_GET['download']) && $_GET['download'] === 'pdf') {
    // Recreate the query for PDF download
    $report_type = $_GET['report_type'];
    $from_date = $_GET['from_date'];
    $to_date = $_GET['to_date'];
    
    // Generate PDF content
    header('Content-Type: application/pdf');
    header('Content-Disposition: attachment; filename="SLPA_Attendance_Report_' . date('Y-m-d') . '.pdf"');
    
    echo "SLPA ATTENDANCE REPORT\n";
    echo "Generated by: $current_user\n";
    echo "Generated on: $current_time\n";
    echo "Period: $from_date to $to_date\n";
    echo "Report Type: " . ucfirst($report_type) . "\n\n";
    exit();
}

if (isset($_GET['download']) && $_GET['download'] === 'excel') {
    // Generate Excel file
    header('Content-Type: application/vnd.ms-excel');
    header('Content-Disposition: attachment; filename="SLPA_Attendance_Report_' . date('Y-m-d') . '.xls"');
    
    echo "<table border='1'>";
    echo "<tr><td colspan='7' style='text-align:center; font-weight:bold; font-size:16px;'>SLPA ATTENDANCE REPORT</td></tr>";
    echo "<tr><td colspan='7'>Generated by: $current_user | Generated on: $current_time</td></tr>";
    echo "<tr><td colspan='7'></td></tr>";
    echo "<tr><th>Employee ID</th><th>Employee Name</th><th>Division</th><th>Section</th><th>Date</th><th>In Times & Locations</th><th>Out Times & Locations</th></tr>";
    
    echo "</table>";
    exit();
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SLPA - Unit Attendance Report</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <style>
        .report-header {
            background: linear-gradient(135deg, #2c3e50 0%, #34495e 100%);
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 30px;
            box-shadow: 0 4px 15px rgba(0,0,0,0.2);
        }
        .slpa-logo {
            width: 60px;
            height: 60px;
            background: white;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            color: #2c3e50;
            font-weight: bold;
            font-size: 24px;
        }
        .form-container {
            background: white;
            padding: 30px;
            border-radius: 15px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.1);
            margin-bottom: 30px;
        }
        .report-container {
            background: white;
            padding: 30px;
            border-radius: 15px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.1);
        }
        .btn-custom {
            background: linear-gradient(135deg, #3498db, #2980b9);
            border: none;
            padding: 12px 30px;
            border-radius: 25px;
            color: white;
            font-weight: 600;
            transition: all 0.3s ease;
        }
        .btn-custom:hover {
            transform: translateY(-2px);
            box-shadow: 0 6px 20px rgba(52, 152, 219, 0.4);
            color: white;
        }
        .btn-download {
            background: linear-gradient(135deg, #27ae60, #2ecc71);
            border: none;
            padding: 10px 25px;
            border-radius: 20px;
            color: white;
            font-weight: 600;
            transition: all 0.3s ease;
            margin: 0 5px;
        }
        .btn-download:hover {
            transform: translateY(-2px);
            box-shadow: 0 6px 20px rgba(46, 204, 113, 0.4);
            color: white;
        }
        .form-control {
            border-radius: 10px;
            border: 2px solid #e9ecef;
            padding: 12px 15px;
            transition: all 0.3s ease;
        }
        .form-control:focus {
            border-color: #3498db;
            box-shadow: 0 0 0 0.2rem rgba(52, 152, 219, 0.25);
        }
        .table {
            border-radius: 10px;
            overflow: hidden;
            box-shadow: 0 4px 15px rgba(0,0,0,0.1);
        }
        .table thead th {
            background: linear-gradient(135deg, #34495e, #2c3e50);
            color: white;
            border: none;
            padding: 15px;
            font-weight: 600;
        }
        .table tbody tr:hover {
            background-color: #f8f9fa;
            transform: scale(1.01);
            transition: all 0.2s ease;
        }
        .report-meta {
            background: #f8f9fa;
            padding: 20px;
            border-radius: 10px;
            margin-bottom: 20px;
            border-left: 5px solid #3498db;
        }
        .status-badge {
            padding: 5px 15px;
            border-radius: 20px;
            font-size: 12px;
            font-weight: 600;
        }
        .status-in {
            background: #d4edda;
            color: #155724;
        }
        .status-out {
            background: #f8d7da;
            color: #721c24;
        }
        body {
            background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
            min-height: 100vh;
        }
        
        /* Print styles */
        @media print {
            body {
                background: white !important;
                font-size: 12px;
            }
            .screen-only {
                display: none !important;
            }
            .print-only {
                display: block !important;
            }
            .report-header, .form-container {
                display: none !important;
            }
            .report-container {
                box-shadow: none !important;
                padding: 0 !important;
                margin: 0 !important;
            }
            .table {
                font-size: 11px;
            }
            .table th, .table td {
                padding: 6px !important;
                border: 1px solid #000 !important;
            }
            .table thead th {
                background: #f8f9fa !important;
                color: #000 !important;
            }
            .status-badge {
                background: none !important;
                border: 1px solid #000 !important;
                color: #000 !important;
                padding: 2px 6px;
            }
        }
    </style>
</head>
<body>

<div class="container-fluid py-4">
    <!-- Header Section -->
    <div class="report-header">
        <div class="row align-items-center">
            <div class="col-auto">
                <div class="slpa-logo">
                    <i class="fas fa-anchor"></i>
                </div>
            </div>
            <div class="col">
                <h1 class="mb-1"><i class="fas fa-chart-line me-2"></i>SLPA Unit Attendance Report</h1>
                <p class="mb-0 opacity-75">Sri Lanka Port Authority - Comprehensive Attendance Management System</p>
            </div>
            <div class="col-auto text-end">
                <small class="d-block opacity-75">Generated by: <strong><?php echo htmlspecialchars($current_user); ?></strong></small>
                <small class="d-block opacity-75">Generated on: <strong><?php echo $current_time; ?></strong></small>
            </div>
        </div>
    </div>

    <!-- Search Form -->
    <div class="form-container">
        <h3 class="mb-4"><i class="fas fa-search me-2"></i>Generate Attendance Report</h3>
        <form method="POST" id="reportForm">
            <div class="row">
                <div class="col-md-3 mb-3">
                    <label for="report_type" class="form-label"><i class="fas fa-list me-1"></i>Report Type</label>
                    <select class="form-control" id="report_type" name="report_type" required>
                        <option value="">Select Type</option>
                        <option value="individual">Individual Employee</option>
                        <option value="group">Group/Division</option>
                    </select>
                </div>
                
                <div class="col-md-3 mb-3" id="employee_section" style="display: none;">
                    <label for="employee_ID" class="form-label"><i class="fas fa-user me-1"></i>Employee ID</label>
                    <input type="text" class="form-control" id="employee_ID" name="employee_ID" placeholder="Enter Employee ID">
                </div>
                
                <div class="col-md-3 mb-3" id="division_section" style="display: none;">
                    <label for="division" class="form-label"><i class="fas fa-building me-1"></i>Division</label>
                    <select class="form-control" id="division" name="division">
                        <option value="">All Divisions</option>
                        <?php
                        // Populate divisions from database
                        $div_query = "SELECT division_id, division_name FROM divisions ORDER BY division_name";
                        $div_result = mysqli_query($connect, $div_query);
                        if ($div_result) {
                            while ($div_row = mysqli_fetch_assoc($div_result)) {
                                echo "<option value='" . $div_row['division_id'] . "'>" . htmlspecialchars($div_row['division_name']) . "</option>";
                            }
                        }
                        ?>
                    </select>
                </div>
                
                <div class="col-md-3 mb-3" id="section_section" style="display: none;">
                    <label for="section" class="form-label"><i class="fas fa-layer-group me-1"></i>Section</label>
                    <select class="form-control" id="section" name="section">
                        <option value="all">All Sections</option>
                        <?php
                        // Populate sections from database
                        $sec_query = "SELECT section_id, section_name FROM sections ORDER BY section_name";
                        $sec_result = mysqli_query($connect, $sec_query);
                        if ($sec_result) {
                            while ($sec_row = mysqli_fetch_assoc($sec_result)) {
                                echo "<option value='" . $sec_row['section_id'] . "'>" . htmlspecialchars($sec_row['section_name']) . "</option>";
                            }
                        }
                        ?>
                    </select>
                </div>
            </div>
            
            <div class="row">
                <div class="col-md-4 mb-3">
                    <label for="from_date" class="form-label"><i class="fas fa-calendar-alt me-1"></i>From Date</label>
                    <input type="date" class="form-control" id="from_date" name="from_date" required>
                </div>
                
                <div class="col-md-4 mb-3">
                    <label for="to_date" class="form-label"><i class="fas fa-calendar-alt me-1"></i>To Date</label>
                    <input type="date" class="form-control" id="to_date" name="to_date" required>
                </div>
                
                <div class="col-md-4 mb-3 d-flex align-items-end">
                    <button type="submit" class="btn btn-custom">
                        <i class="fas fa-chart-bar me-2"></i>Generate Report
                    </button>
                </div>
            </div>
        </form>
    </div>

<?php
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $report_type = $_POST['report_type'];
    $from_date = $_POST['from_date'];
    $to_date = $_POST['to_date'];

    // Initialize SQL query and parameters
    $sql = "";
    $params = [];

    if ($report_type === 'individual') {
        $employee_ID = $_POST['employee_ID'];
        $sql = "SELECT a.employee_ID, 
                       COALESCE(e.employee_name, 'Unknown Employee') as employee_name, 
                       COALESCE(d.division_name, 'Unknown Division') as division_name, 
                       COALESCE(s.section_name, 'Unknown Section') as section_name, 
                       a.date_,
                       a.scan_type, a.time_, 
                       COALESCE(f.location, 'Unknown Location') as location
                FROM attendance a
                LEFT JOIN employees e ON a.employee_ID = e.employee_ID
                LEFT JOIN divisions d ON e.division = d.division_id
                LEFT JOIN sections s ON e.section = s.section_id
                LEFT JOIN fingerprints f ON f.fingerprint_id = a.fingerprint_id
                WHERE a.employee_ID = ? AND a.date_ BETWEEN ? AND ?
                ORDER BY a.date_, a.time_";
        $params = [$employee_ID, $from_date, $to_date];
    } else if ($report_type === 'group') {
        $division = $_POST['division'];
        $section = $_POST['section'];

        $sql = "SELECT a.employee_ID, 
                       COALESCE(e.employee_name, 'Unknown Employee') as employee_name, 
                       COALESCE(d.division_name, 'Unknown Division') as division_name, 
                       COALESCE(s.section_name, 'Unknown Section') as section_name, 
                       a.date_,
                       a.scan_type, a.time_, 
                       COALESCE(f.location, 'Unknown Location') as location
                FROM attendance a
                LEFT JOIN employees e ON a.employee_ID = e.employee_ID
                LEFT JOIN divisions d ON e.division = d.division_id
                LEFT JOIN sections s ON e.section = s.section_id
                LEFT JOIN fingerprints f ON f.fingerprint_id = a.fingerprint_id
                WHERE a.date_ BETWEEN ? AND ?";
        $params = [$from_date, $to_date];

        if (!empty($division)) {
            $sql .= " AND e.division = ?";
            $params[] = $division;
        }

        if ($section != 'all' && !empty($section)) {
            $sql .= " AND e.section = ?";
            $params[] = $section;
        }

        $sql .= " ORDER BY a.employee_ID, a.date_, a.time_";
    }

    $stmt = mysqli_prepare($connect, $sql);
    
    if ($report_type === 'individual') {
        mysqli_stmt_bind_param($stmt, "sss", ...$params);
    } else if ($report_type === 'group') {
        $types = str_repeat('s', count($params));
        mysqli_stmt_bind_param($stmt, $types, ...$params);
    }

    mysqli_stmt_execute($stmt);
    $result = mysqli_stmt_get_result($stmt);

    // Process and analyze the data first
    $attendance_data = [];
    $total_check_ins = 0;
    $total_check_outs = 0;
    $complete_attendance_days = 0;
    $total_working_hours = 0;
    $unique_employees = [];
    $unique_devices = [];

    while ($row = mysqli_fetch_assoc($result)) {
        $key = $row['employee_ID'] . '_' . $row['date_'];
        
        if (!isset($attendance_data[$key])) {
            $attendance_data[$key] = [
                'employee_ID' => $row['employee_ID'],
                'employee_name' => $row['employee_name'],
                'division_name' => $row['division_name'],
                'section_name' => $row['section_name'],
                'date_' => $row['date_'],
                'check_in_times' => [],
                'check_out_times' => [],
                'locations' => []
            ];
        }
        
        $unique_employees[$row['employee_ID']] = true;
        $unique_devices[$row['location']] = true;
        
        if ($row['scan_type'] === 'IN') {
            $attendance_data[$key]['check_in_times'][] = $row['time_'] . " (" . $row['location'] . ")";
            $total_check_ins++;
        } else if ($row['scan_type'] === 'OUT') {
            $attendance_data[$key]['check_out_times'][] = $row['time_'] . " (" . $row['location'] . ")";
            $total_check_outs++;
        }
    }

    // Calculate statistics
    $total_employees = count($unique_employees);
    $total_records = count($attendance_data);
    $devices_used = count($unique_devices);
    
    foreach ($attendance_data as $record) {
        if (!empty($record['check_in_times']) && !empty($record['check_out_times'])) {
            $complete_attendance_days++;
            // Calculate working hours if both check-in and check-out exist
            $first_in = explode(' (', $record['check_in_times'][0])[0];
            $last_out = explode(' (', end($record['check_out_times']))[0];
            $in_time = strtotime($first_in);
            $out_time = strtotime($last_out);
            if ($out_time > $in_time) {
                $total_working_hours += ($out_time - $in_time) / 3600;
            }
        }
    }
    
    $avg_working_hours = $complete_attendance_days > 0 ? round($total_working_hours / $complete_attendance_days, 1) : 0;
    $report_period_days = ceil((strtotime($to_date) - strtotime($from_date)) / (60*60*24)) + 1;

    // Generate report 
    if ($total_records > 0) {
        echo "<div class='report-container'>";
        
        // Print-specific header and statistics (hidden on screen, visible when printing)
        echo "<div class='print-only' style='display: none;'>";
        echo "<div style='text-align: center; margin-bottom: 30px; border-bottom: 2px solid #2c3e50; padding-bottom: 20px;'>";
        echo "<h1 style='color: #2c3e50; margin: 0;'>SLPA Unit Attendance Report</h1>";
        echo "<p style='margin: 5px 0; font-size: 14px;'>Sri Lanka Port Authority - Comprehensive Attendance Management System</p>";
        echo "<p style='margin: 5px 0; font-size: 12px;'>Generated by: " . htmlspecialchars($current_user) . " | Generated on: " . date('M d, Y \a\t H:i:s') . "</p>";
        echo "</div>";
        
        // Statistics section for print
        echo "<div style='background: #f8f9fa; padding: 20px; margin-bottom: 30px; border: 1px solid #ddd;'>";
        echo "<h3 style='text-align: center; margin-bottom: 20px; color: #2c3e50;'>INFORMATION SYSTEMS</h3>";
        echo "<p style='text-align: center; margin-bottom: 20px; font-weight: bold;'>All Sections</p>";
        
        echo "<table style='width: 100%; border-collapse: collapse; margin-bottom: 20px;'>";
        echo "<tr>";
        echo "<td style='padding: 8px; border: 1px solid #ddd; background: #f1f1f1; font-weight: bold; text-align: center;'>Total Records</td>";
        echo "<td style='padding: 8px; border: 1px solid #ddd; text-align: center; font-size: 18px; font-weight: bold; color: #2c3e50;'>" . $total_records . "</td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td style='padding: 8px; border: 1px solid #ddd; text-align: center; font-size: 12px;'>Attendance days</td>";
        echo "<td style='padding: 8px; border: 1px solid #ddd;'></td>";
        echo "</tr>";
        
        echo "<tr>";
        echo "<td style='padding: 8px; border: 1px solid #ddd; background: #f1f1f1; font-weight: bold; text-align: center;'>Total Employees</td>";
        echo "<td style='padding: 8px; border: 1px solid #ddd; text-align: center; font-size: 18px; font-weight: bold; color: #2c3e50;'>" . $total_employees . "</td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td style='padding: 8px; border: 1px solid #ddd; text-align: center; font-size: 12px;'>Unique employees</td>";
        echo "<td style='padding: 8px; border: 1px solid #ddd;'></td>";
        echo "</tr>";
        
        echo "<tr>";
        echo "<td style='padding: 8px; border: 1px solid #ddd; background: #f1f1f1; font-weight: bold; text-align: center;'>Total Check-ins</td>";
        echo "<td style='padding: 8px; border: 1px solid #ddd; text-align: center; font-size: 18px; font-weight: bold; color: #2c3e50;'>" . $total_check_ins . "</td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td style='padding: 8px; border: 1px solid #ddd; text-align: center; font-size: 12px;'>IN scans recorded</td>";
        echo "<td style='padding: 8px; border: 1px solid #ddd;'></td>";
        echo "</tr>";
        
        echo "<tr>";
        echo "<td style='padding: 8px; border: 1px solid #ddd; background: #f1f1f1; font-weight: bold; text-align: center;'>Total Check-outs</td>";
        echo "<td style='padding: 8px; border: 1px solid #ddd; text-align: center; font-size: 18px; font-weight: bold; color: #2c3e50;'>" . $total_check_outs . "</td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td style='padding: 8px; border: 1px solid #ddd; text-align: center; font-size: 12px;'>OUT scans recorded</td>";
        echo "<td style='padding: 8px; border: 1px solid #ddd;'></td>";
        echo "</tr>";
        
        echo "<tr>";
        echo "<td style='padding: 8px; border: 1px solid #ddd; background: #f1f1f1; font-weight: bold; text-align: center;'>Complete Days</td>";
        echo "<td style='padding: 8px; border: 1px solid #ddd; text-align: center; font-size: 18px; font-weight: bold; color: #2c3e50;'>" . $complete_attendance_days . "</td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td style='padding: 8px; border: 1px solid #ddd; text-align: center; font-size: 12px;'>Days with both IN & OUT</td>";
        echo "<td style='padding: 8px; border: 1px solid #ddd;'></td>";
        echo "</tr>";
        
        echo "<tr>";
        echo "<td style='padding: 8px; border: 1px solid #ddd; background: #f1f1f1; font-weight: bold; text-align: center;'>Avg. Working Hours</td>";
        echo "<td style='padding: 8px; border: 1px solid #ddd; text-align: center; font-size: 18px; font-weight: bold; color: #2c3e50;'>" . $avg_working_hours . "h</td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td style='padding: 8px; border: 1px solid #ddd; text-align: center; font-size: 12px;'>Per complete day</td>";
        echo "<td style='padding: 8px; border: 1px solid #ddd;'></td>";
        echo "</tr>";
        
        echo "<tr>";
        echo "<td style='padding: 8px; border: 1px solid #ddd; background: #f1f1f1; font-weight: bold; text-align: center;'>Devices Used</td>";
        echo "<td style='padding: 8px; border: 1px solid #ddd; text-align: center; font-size: 18px; font-weight: bold; color: #2c3e50;'>" . $devices_used . "</td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td style='padding: 8px; border: 1px solid #ddd; text-align: center; font-size: 12px;'>Fingerprint machines</td>";
        echo "<td style='padding: 8px; border: 1px solid #ddd;'></td>";
        echo "</tr>";
        
        echo "<tr>";
        echo "<td style='padding: 8px; border: 1px solid #ddd; background: #f1f1f1; font-weight: bold; text-align: center;'>Report Period</td>";
        echo "<td style='padding: 8px; border: 1px solid #ddd; text-align: center; font-size: 18px; font-weight: bold; color: #2c3e50;'>" . $report_period_days . "</td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td style='padding: 8px; border: 1px solid #ddd; text-align: center; font-size: 12px;'>Days covered</td>";
        echo "<td style='padding: 8px; border: 1px solid #ddd;'></td>";
        echo "</tr>";
        echo "</table>";
        
        echo "<div style='margin-top: 20px;'>";
        echo "<div style='float: left;'>";
        echo "<p style='margin: 5px 0; font-size: 12px;'><strong>Report Period</strong></p>";
        echo "<p style='margin: 5px 0; font-size: 12px;'>" . date('M d, Y', strtotime($from_date)) . " to " . date('M d, Y', strtotime($to_date)) . "</p>";
        echo "<p style='margin: 5px 0; font-size: 12px;'><strong>Generated</strong></p>";
        echo "<p style='margin: 5px 0; font-size: 12px;'>" . date('M d, Y \a\t H:i:s') . "</p>";
        echo "</div>";
        echo "<div style='float: right; text-align: right;'>";
        echo "<p style='margin: 5px 0; font-size: 12px;'><strong>Generated by</strong></p>";
        echo "<p style='margin: 5px 0; font-size: 12px;'>" . htmlspecialchars($current_user) . "</p>";
        echo "</div>";
        echo "<div style='clear: both;'></div>";
        echo "</div>";
        echo "</div>";
        echo "</div>";
        
        // Screen-only report meta information
        echo "<div class='screen-only report-meta'>";
        echo "<div class='row'>";
        echo "<div class='col-md-6'>";
        echo "<h4><i class='fas fa-info-circle me-2'></i>Report Details</h4>";
        echo "<p><strong>Report Type:</strong> " . ucfirst($report_type) . "</p>";
        echo "<p><strong>Date Range:</strong> " . $from_date . " to " . $to_date . "</p>";
        echo "<p><strong>Total Records:</strong> " . $total_records . "</p>";
        echo "</div>";
        echo "<div class='col-md-6 text-end'>";
        echo "<h4><i class='fas fa-download me-2'></i>Download Options</h4>";
        
        // Download buttons
        $download_params = http_build_query([
            'report_type' => $report_type,
            'from_date' => $from_date,
            'to_date' => $to_date
        ]);
        
        echo "<a href='?download=pdf&$download_params' class='btn btn-download'>";
        echo "<i class='fas fa-file-pdf me-1'></i>Download PDF";
        echo "</a>";
        
        echo "<a href='?download=excel&$download_params' class='btn btn-download'>";
        echo "<i class='fas fa-file-excel me-1'></i>Download Excel";
        echo "</a>";
        
        echo "<button onclick='window.print()' class='btn btn-download'>";
        echo "<i class='fas fa-print me-1'></i>Print Report";
        echo "</button>";
        
        echo "</div>";
        echo "</div>";
        echo "</div>";
        
        echo "<h2><i class='fas fa-table me-2'></i>Attendance Report</h2>";
        echo "<div class='table-responsive'>";
        echo "<table class='table table-striped table-hover'>";
        echo "<thead><tr>";
        echo "<th><i class='fas fa-id-badge me-1'></i>Employee ID</th>";
        echo "<th><i class='fas fa-user me-1'></i>Employee Name</th>";
        echo "<th><i class='fas fa-building me-1'></i>Division</th>";
        echo "<th><i class='fas fa-layer-group me-1'></i>Section</th>";
        echo "<th><i class='fas fa-calendar me-1'></i>Date</th>";
        echo "<th><i class='fas fa-sign-in-alt me-1'></i>First Check-In</th>";
        echo "<th><i class='fas fa-sign-out-alt me-1'></i>Last Check-Out</th>";
        echo "</tr></thead>";
        echo "<tbody>";

        // Display the processed attendance data
        foreach ($attendance_data as $record) {
            echo "<tr>";
            echo "<td><strong>" . htmlspecialchars($record['employee_ID']) . "</strong></td>";
            echo "<td>" . htmlspecialchars($record['employee_name']) . "</td>";
            echo "<td>" . htmlspecialchars($record['division_name']) . "</td>";
            echo "<td>" . htmlspecialchars($record['section_name']) . "</td>"; 
            echo "<td><span class='badge bg-primary'>" . date('M d, Y', strtotime($record['date_'])) . "</span></td>";
            
            // First check-in
            echo "<td>";
            if (!empty($record['check_in_times'])) {
                $first_check_in = $record['check_in_times'][0];
                echo "<span class='status-badge status-in'>" . $first_check_in . "</span>";
                if (count($record['check_in_times']) > 1) {
                    echo "<br><small class='text-muted'>+" . (count($record['check_in_times']) - 1) . " more</small>";
                }
            } else {
                echo "<span class='text-muted'>No check-in</span>";
            }
            echo "</td>";
            
            // Last check-out
            echo "<td>";
            if (!empty($record['check_out_times'])) {
                $last_check_out = end($record['check_out_times']);
                echo "<span class='status-badge status-out'>" . $last_check_out . "</span>";
                if (count($record['check_out_times']) > 1) {
                    echo "<br><small class='text-muted'>+" . (count($record['check_out_times']) - 1) . " more</small>";
                }
            } else {
                echo "<span class='text-muted'>No check-out</span>";
            }
            echo "</td>";
            echo "</tr>";
        }

        echo "</tbody>";
        echo "</table>";
        echo "</div>";
    } else {
        echo "<div class='report-container'>";
        echo "<div class='alert alert-warning text-center'>";
        echo "<i class='fas fa-exclamation-triangle fa-3x mb-3'></i>";
        echo "<h4>No Records Found</h4>";
        echo "<p>No attendance records found for the selected criteria.</p>";
        echo "<small>Please try adjusting your search parameters.</small>";
        echo "</div>";
        echo "</div>";
    }

    mysqli_stmt_close($stmt);
}
?>
</div>

<script>
// Dynamic form controls
document.getElementById('report_type').addEventListener('change', function() {
    var reportType = this.value;
    var employeeSection = document.getElementById('employee_section');
    var divisionSection = document.getElementById('division_section');
    var sectionSection = document.getElementById('section_section');
    
    if (reportType === 'individual') {
        employeeSection.style.display = 'block';
        divisionSection.style.display = 'none';
        sectionSection.style.display = 'none';
        
        document.getElementById('employee_ID').required = true;
        document.getElementById('division').required = false;
    } else if (reportType === 'group') {
        employeeSection.style.display = 'none';
        divisionSection.style.display = 'block';
        sectionSection.style.display = 'block';
        
        document.getElementById('employee_ID').required = false;
        document.getElementById('division').required = false;
    } else {
        employeeSection.style.display = 'none';
        divisionSection.style.display = 'none';
        sectionSection.style.display = 'none';
    }
});

// Set default dates to last 7 days
document.getElementById('from_date').value = new Date(new Date().setDate(new Date().getDate() - 7)).toISOString().split('T')[0];
document.getElementById('to_date').value = new Date().toISOString().split('T')[0];
</script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
